name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test_core_function:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test acceleration function
        run: cd driver && make test

  test_installation_and_cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test in the docker image
        run: docker build -f Dockerfile.ubuntu
